### ISSUE TITLE
Future API

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-proton#108]
we need for Vert.x 4 to have `Future` based API that will return context futures that are now supported by the Vert.x API.

**Comment by gemmellr** [comment]
Isn't that something vertx-amqp-client is better suited to cater for?

Vertx-proton's use of handlers nicely suits the protocol-handling nature of its usage, coupled with the fact the protocol is mostly symmetric and peer to peer and so those handlers are used (often to different effect) on both 'client' and 'server' ends of a connection (with vertx-proton seeing a fair bit of use as a server). I don't think adding a future based API makes a great deal of sense for vertx-proton personally given that, and adding it to whats there would rather muddy the existing API for cases the future based API wont work well.

I also don't see a particular need given vertx-proton mainly always acted as a building block for other things, like the bridge and vertx-amqp-client. Its never been listed on the website.

**Comment by vietj** [comment]
@gemmellr let me explain the main reason I opened this issue.

In Vert.x 4, the `Future` are becoming contextual, i.e they are attached to a Vert.x context. So when you write:

```
Future<NetSocket> fut = client.connect(address);
ns.setHandler(ns -> ...);
```

The handler will run on a context even if the `Future` was resolved before the handler is set  (let's imagine the code is executed from a non vertx thread).

The vertx-amqp-client will be rewritten to have this model of course. When the amqp client will delegate to vertx proton then vertx-proton might create a different context that the amqp client will use, i.e imagine this code executed from a non vertx thread:

```java
Future<AmqpConnection> future =  amqpClient.connect();
future.setHandler(conn -> ...);
```

And in AMQP client we will have:

```java
Context ctx = vertx.getOrCreateContext(); // Will return the current context or a new context if executed outside event-loop
Promise<AmqpConnection> promise = ctx.promise();
proton.connect(..., ar -> {
  .... some code to create a connection
  promise.complete(connection)
});
```

The current proton connect implementation will also use `getOrCreateContext()` internally and since we are not on a Vert.x thread will use a different event-loop.

The ideal way is that vertx proton returns a `Future<ProtonConnection>` and the amqp client is rewritten to use `map` / `flatMap` operations:

```java
Future<ProtonConnection> fut = proton.connect(...);
Future<AmqpConnection> fut2 = fut.flatMap(...);
return fut2;
```

**Comment by vietj** [comment]
Note that now `NetClient` used by vertx proton returns `Future` and if you call connect with an handler, it simply calls the `Future` method and set the handler on it.

**Comment by gemmellr** [comment]
The core of vertx-proton is inherently single threaded so you aren't allowed to call it from multiple threads in general, and its model has always been that you either ensured there is a context upfront and call ProtonClient.connect(..) on it plus use it for further interactions, or you could call ProtonClient.connect(..) from a non-vertx thread but then always have to use the handler context for further interacting with the resulting connection. It doesn't do getOrCreateContext() itself but defers directly to the NetClient.connect(..) which did and either created a new context if none was set and used it for callbacks, or picked up the context it was called on and used that. It sets the netSocket.handler(..) only in the connect callback, once the context was available either way.

As such I'd expect vertx-amqp-client to either be using an existing context or creating a new one first, and running vertx-proton operations through it. Thats what it seems to be doing now, so I don't understand why that need actually change for the above.

That said, if all you really want are "Future<ProtonConnection> connect(..)" methods which do that, then I dont have strong feelings on that.

**Comment by gemmellr** [comment]
i.e is this all you mean? https://github.com/vert-x3/vertx-proton/compare/future-connect

**Comment by vietj** [comment]
@gemmellr you nailed it but that would be for other async operations too
