### ISSUE TITLE
Exposing the updateSSLOptions() method of the NetServer class

### ISSUE THREAD

**Issue by pcHwang2** [vert-x3/vertx-proton#137]
I need to hot load amqp server certificate, NetServer's updateSSLOptions() method can satisfy my requirement very well, but the ProtonServerImpl class doesn't expose this method, so I need to call it by reflection, which is not friendly to the subsequent maintenance, is there any other better way to satisfy my requirement of hot load amqp server certificate, or is there any plan to expose the NetServer's updateSSLOptions() method in the ProtonServerImpl class in future?

**Comment by vietj** [comment]
simple provide a PR that exposes it and well' review and merge it

**Comment by pcHwang2** [comment]
Okay, I've opened a PR.
