### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by sophokles73** [vert-x3/vertx-proton#14]
Hi,

I was playing around with vertx-proton, considering it for use in an Eclipse open source project. However, in order to do so I would need to know what license the code is distributed under.

Since vert.x is an Eclipse project I was hoping that you would also use EPL?

Thanks,
Kai

**Comment by cescoffier** [comment]
I guess it will use the dual license model Vert.x components use:

* ASL 2.0
* EPL

**Comment by purplefox** [comment]
Only Vert.x core is dual licensed. The rest of the official components are just ASL2

**Comment by purplefox** [comment]
All Vert.x official stack components should have a LICENSE.txt in the root. If there's not one there it can be copied from another component e.g. vertx-web

**Comment by cescoffier** [comment]
A couple of other component are using the dual license, such as vert.x shell (https://github.com/vert-x3/vertx-shell/blob/master/src/main/java/io/vertx/ext/shell/ShellServer.java).

**Comment by sophokles73** [comment]
In the end I do not really care whether it's ASL 2.0 or EPL 1.0. However, I DO need to know the license in order to be able to use vertx-proton at all (and being able to contribute anything).

**Comment by purplefox** [comment]
I don't know why vertx-shell and others are dual licensed.

The policy has always been to license non Vert.x core components as ASL 2.0 only. I guess it doesn't matter too much if other components are dual licensed but I think it would be better to be consistent.

The LICENSE.txt should be copied into each component project.

**Comment by hekonsek** [comment]
@sophokles73 Anyway - we are good, I guess. ASL 2.0 can be used in Eclipse projects.

**Comment by sophokles73** [comment]
I agree but still someone needs to put the LICENSE.txt file in there before we can use it ...

**Comment by purplefox** [comment]
@gemmellr is the maintainer of the module.

But... please bear in mind the work here (in initial-work) branch is still a development work in progress and I wouldn't recommend using it in production yet.
Once it's ready it will end up in master as per the development process on the wiki :)

**Comment by hekonsek** [comment]
I would even say that someone has to release the project to Maven repo before we use it :) . Guys, do you have any estimates regarding the very first release of vertx-proton?

**Comment by vietj** [comment]
@hekonsek we hope a first version in Vert.x 3.3, at least as "tech preview"

**Comment by hekonsek** [comment]
No worries Tim, our project has have time before getting anywhere into production. We can wait for Robbie to finish the job or even help him a little bit :) .

**Comment by hekonsek** [comment]
@vietj Awesome! Thanks!

**Comment by gemmellr** [comment]
I've added a LICENCE.txt file containing the ASLv2, which is what I've been assuming the code was under since I've been contributing.
