### ISSUE TITLE
SASL support on server side

### ISSUE THREAD

**Issue by sophokles73** [vert-x3/vertx-proton#18]
Hi,

I have been using vertx-proton to implement an AMQP server component. However, I am now stuck in figuring out how to configure security, i.e. authentication of clients.

Taking a look at the source code (in particular `ProtonServerImpl`) it looks like the only SASL mechanism currently supported (hard wired into the code) is *ANONYMOUS*. Is that right?

Assuming that at some time another mechanism is supported, what API could I use to actually determine the authenticated client's identity (e.g. its username used in username/password based authentication)? I could imagine having a `ProtonConnection.getRemotePrincipal()` or something similar. Or maybe at the link level, i.e. `ProtonLink.getRemotePrincipal()`?

Regards,
Kai

**Comment by gemmellr** [comment]
Thats right, the server bit only does ANONYMOUS currently (you could perhaps require ssl client certificates, but it would still only do anon SASL and there would be no way to determine which cert was used). Any 'determine identity' bits added would likely be at the transport or connection level rather than the links.

**Comment by sophokles73** [comment]
> Any 'determine identity' bits added would likely be at the transport or connection level rather than the links.

Yes, I guess that makes more sense.

So, are you planning to add support for additional SASL mechanisms at the server side? In the Hono project we would like to use the [OAUTHBEARER SASL mechanism](http://tools.ietf.org/html/rfc7628) to use OAuth bearer tokens for authenticating clients. In order to do so, we would need to have some API available on the `ProtonServer` or `ProtonServerOptions` for registering a `ProtonSaslAuthenticator`, I guess...

**Comment by gemmellr** [comment]
It isn't something I have plans for, the existing bits around there are just the minimal to let the client and server do different things, I haven't given much thought yet to expanding it beyond that. Either replacing the authenticator or making the one there smart enough to handle additional mechs could be possible routes.

**Comment by hekonsek** [comment]
Kai, do you think that extending server authenticator to be pluggable would be enough for our current needs?

**Comment by sophokles73** [comment]
Yes, I guess that would be exactly what we need. It should be possible to somehow *register* user (Hono) provided implementations of `ProtonSaslAuthenticator`. We could then implement it as part of Hono and *plug it into* proton vertx during startup ...

**Comment by hekonsek** [comment]
What do you guys think about this (https://github.com/vert-x3/vertx-proton/pull/24) pull request? It should resolve the issue of pluggability of the authenticators.
