### ISSUE TITLE
avoid firing sendQueueDrainHandler for each transfer sent

### ISSUE THREAD

**Issue by ppatierno** [vert-x3/vertx-proton#19]
The fireLinkFlow() is called every time the LINK_FLOW event is catched inside the ProtonTrasport.
In general it's always raised when a flow performative is received and when a transfer performative is received.
The underlying ProtonJ implementation has a flag named _emitFlowEventOnSend that allow to configure the second condition : it's possible to avoid raising the event for each transfer performative received.
The Trasport (in ProtonJ) allows to set this flag with the exposed method setEmitFlowEventOnSend().
It could be useful to using it and make the event raising configurable in Vert.x Proton as well.

**Comment by gemmellr** [comment]
PR merged, thanks for the contribution :)

I've tweaked the title a bit to reflect that it is outbound transfers that provoke the synthetic flow events.

**Comment by ppatierno** [comment]
@gemmellr no worries ... you're the boss ;)
