### ISSUE TITLE
Client creating malformed frames

### ISSUE THREAD

**Issue by lulf** [vert-x3/vertx-proton#27]
Getting a lot of errors when using vertx-proton as a sender in my setup with 1 sender, 1 qpid
dispatch router, and 1 qpid proton receiver (C client).

The errors are usually either about malformed frames or wrong type constructors. Most of the times I
run the test, it stops with:

io.vertx.core.impl.NoStackTraceThrowable: Error{condition=amqp:connection:framing-error, description='malformed frame', info=null}

But some times it continues. 

The receiver is invoked as such: 
./receiver -a 192.168.1.76:5674 -c 0 -s amqp-test

Configs for qdrouter and client code is attached.

[simple_queue.txt](https://github.com/vert-x3/vertx-proton/files/302670/simple_queue.txt)
[VertxTester.txt](https://github.com/vert-x3/vertx-proton/files/302671/VertxTester.txt)

**Comment by gemmellr** [comment]
vertx-proton satisfies Proton's own requirement for singled threaded use by in turn requiring that you always use the event loop thread to do the work. Your tester is doing most of the actions on the main thread currently and so the two threads will likely be acting concurrently and corrupting the frames.

You can satisfy that requirement by doing things in the callbacks from connect/open etc, or by running things on the Vertx [Event Loop] Context used by the thread when those callbacks are made, and you can drop all the synchronized blocks.

**Comment by lulf** [comment]
Ah, thank you! Using the vertx event loop is the solution I was looking for originally.

**Comment by gemmellr** [comment]
Added label to avoid the Issue being in release notes.
