### ISSUE TITLE
ProtonSaslAuthenticator is scoped to ProtonServer not ProtonConnection

### ISSUE THREAD

**Issue by sophokles73** [vert-x3/vertx-proton#30]
Hi,

I have started to play around with the new `ProtonSaslAuthenticator` interface in order to implement support for SASL based authentication in our Hono server. I tried to follow the `TestAuthenticator` used in `ProtonServerImplTest` to implement PLAIN ath on the server. However, the example authenticator implementation keeps state in private fields across invocations of its `init()`, `process()` and `succeeded()` methods which makes me wonder how this is supposed to work for multiple concurrent connection requests that need to be authenticated. Wouldn't it make more sense to create a separate instance of `ProtonSaslAuthenticator` for every connection to be established instead of having one instance per server?

Kai

**Comment by gemmellr** [comment]
It would make more sense, yes. It started off that way, but I somehow didn't realise the previous proposed changes had flipped it. The setter that was added should probably be for a factory rather than an authenticator itself.

**Comment by gemmellr** [comment]
I've pushed a change on the _auth-factory_ branch, if you could give it a try out and see how you get on with it I'll merge it for 3.3.3.

**Comment by sophokles73** [comment]
This looks good, thanks for the prompt reply :+1:

**Comment by gemmellr** [comment]
Thanks for checking it out, now merged. I wanted to get a change in quickly as I'll be disappearing for the next couple of weeks.
