### ISSUE TITLE
ProtonSaslAuthenticator's API seems to require synchronous processing of credentials

### ISSUE THREAD

**Issue by sophokles73** [vert-x3/vertx-proton#31]
I am currently trying to implement an authenticator that needs to interact with another (remote) node to validate credentials. My understanding is that this should be done within `ProtonSaslAuthenticator.process()`. However, this method is supposed to return a boolean indicating successful processing of the peer's response. When I need to reach out to a remote peer for validating the credentials it might take some time to receive the answer and I do not want to block the event loop.
Any ideas? Maybe the `process()` method should not return a boolean but instead accept a `Handler` as an argument to be notified when processing is finished?

**Comment by gemmellr** [comment]
I have made some updates to accommodate async completion on the _async-auth-process_ branch, if you'd like to give it a test out and report how you get on with them.

**Comment by gemmellr** [comment]
I have just pushed the change to master since there is a 3.3.3 release coming any day now. It would still be good if you could give it a try.

**Comment by sophokles73** [comment]
I am currently playing around with it. So far this works for me :-) Thanks for the quick change!
