### ISSUE TITLE
can't get ProtonConnection from ProtonLInk (or ProtonSession)

### ISSUE THREAD

**Issue by grs** [vert-x3/vertx-proton#38]
It would be nice to be able to get the connection a link is associated with. You can get the session, but the session doesn't let you get at the parent connection.

**Comment by gemmellr** [comment]
Agreed, an oversight. The session impl does have a method for getting the connection impl, you could cast and use that as a workaround for now.

**Comment by grs** [comment]
Ah, good point, hadn't noticed that!

**Comment by gemmellr** [comment]
I've exposed a getConnection method on the session. I left the other impl method public for now (it should have been package private), that can be fixed after the next release.
