### ISSUE TITLE
Milestone release

### ISSUE THREAD

**Issue by sophokles73** [vert-x3/vertx-proton#41]
Hi,

I know that you are aligning the release of vertx-proton with the vert.x release schedule. However, the latest commits from @ppatierno regarding the heartbeat and timeout configuration are very important for us to use in the Eclipse Hono project. Would it be possible for you to create a milestone release from current master, e.g. something along the lines of `3.3.4-M1` so that we can retrieve it from Maven Central?

**Comment by gemmellr** [comment]
Essentially all of the components align with the vert.x release schedule. The next release is 3.4.0, and a beta for it is due soon.

Thoughts @vietj ?

**Comment by sophokles73** [comment]
And there would be artifacts being released to Maven Central for the beta?

**Comment by vietj** [comment]
there will be a 3.4.0 beta next week in central

**Comment by sophokles73** [comment]
Thanks guys :+1:

**Comment by gemmellr** [comment]
3.4.0.Beta1 is in central now
