### ISSUE TITLE
Memory leak when connect attempt fails.

### ISSUE THREAD

**Issue by sophokles73** [vert-x3/vertx-proton#51]
`ProtonClientImpl.connectNetClient()` currently does not close the `NetClient` being passed in as a param from the `connect()` methods, if the connect attempt fails.

When the `NetClient` instance is created, the `NetClientImpl` constructor registers a *closeHook* for it in the vert.x `Context`. This hook is removed when `NetClientImpl.close()` is invoked. However, when a connect attempt fails, this method is never invoked and thus the hook is never removed, preventing the (useless) `NetClientImpl` instance from being garbage collected.

**Comment by gemmellr** [comment]
Marked as duplicate to avoid double release notes addition.
