### ISSUE TITLE
JsonObject converter and constructor for Options classes

### ISSUE THREAD

**Issue by michaelkoetter** [vert-x3/vertx-proton#60]
Similar to NetClientOptions and other *Options classes in vert.x, it would be useful if the vertx-proton Options classes had a converter a corresponding constructor, ie. a package-private `NetClientOptionsConverter` class with `toJson` and `fromJson` methods which would be used in a constructor `public NetClientOptions(JsonObject json) {...}`.

**Comment by tsegismont** [comment]
Would you like to contribute this?

2017-11-21 17:53 GMT+01:00 Michael Kötter <notifications@github.com>:

**Comment by gemmellr** [comment]
He already has actually already raised a PR. I was on holiday at the time and forgot to loop back after. I'll give it a look tomorrow.
