### ISSUE TITLE
Provide OSGi metadata

### ISSUE THREAD

**Issue by ctron** [vert-x3/vertx-proton#66]
Vert.x core does provide OSGi metadata in the `MANIFEST.MF` file. It would be good if vertx-proton would also provide OSGi metadata so that consumers of `vertx-proton` can use OSGi.

I would be willing to create a PR for this.

Also see:
 * https://github.com/eclipse/vert.x/blob/master/pom.xml#L610
 * eclipse/hono#475

**Comment by gemmellr** [comment]
Thanks Jens!

**Comment by ctron** [comment]
Thanks for merging!
