### ISSUE TITLE
ProtonSaslClientAuthenticatorImpl should expose SASL outcome

### ISSUE THREAD

**Issue by sophokles73** [vert-x3/vertx-proton#69]
Currently, the client authenticator throws a `SecurityException` if a SASL handshake fails. For client code, there is no way to determine why the handshake has failed because the authenticator does not provide access to the `org.apache.qpid.proton.engine.Sasl.SaslOutcome` that is the cause for the handshake failure. In particular, the difference between `PN_SASL_AUTH` and `PN_SASL_SYS` seems to be relevant because in the former case there is no use in a client re-trying to authenticate, whereas in the latter, a retry might make sense, because the failure might have been caused by a database connection not having been established yet.

I can imagine to throw a custom subclass of `SecurityException` which includes the outcome so that interested client code can examine the cause for the failure and act accordingly.

WDYT?

**Comment by sophokles73** [comment]
I would be happy to create a corresponding PR ...

**Comment by vietj** [comment]
I think it's fine but let's ask @gemmellr his opinion first :-)

**Comment by gemmellr** [comment]
That seems reasonable to me.

**Comment by gemmellr** [comment]
The changes in PR #70 allow discerning the SASL outcome by inspecting the different SaslException returned on connection failure depending on the cause.
