### ISSUE TITLE
Missing free() method on ProtonLink

### ISSUE THREAD

**Issue by calohmn** [vert-x3/vertx-proton#82]
We have a scenario where on the same AMQP connection, we create and close new receiver links multiple times. There we noticed a memory leak - the `ProtonReceiverImpl` objects were not GC'ed.

Looking further into this, the `org.apache.qpid.proton.engine.impl.ConnectionImpl` keeps the (Receiver)Link objects in a linked list (see `_linkHead` and `_linkTail` fields) and it looks like these list items can only be removed by calling the `free()` method on the `org.apache.qpid.proton.engine.Link` object.

The problem is, there is no correponding `free()` method on `io.vertx.proton.ProtonLink`.

That means there is currently no means to free up the closed `ProtonReceiverImpl` or `ProtonSenderImpl` objects (without resorting to reflection).

**Comment by gemmellr** [comment]
I have exposed the method on ProtonLink, and the related case for ProtonSession also.
